---
version: "2.4"
services:
  redis:
    container_name: odysync_redis
    image: redis

  web:
    container_name: odysync_web
    image: odysync
    volumes:
      - ./vol/db:/data
      - ./vol/lbrynet:/root/.local/share/lbry
    ports:
      - 3000:3000
